import type { Metadata } from 'next';
import './globals.css';
import Header from '../components/common/Header';
import Footer from '../components/common/Footer';
import styles from './layout.module.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Grandstander:ital,wght@0,100..900;1,100..900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <div className={styles.page}>
          <div className={styles.header}>
            <Header />
          </div>
          <div className={styles.main}>{children}</div>
          <div className={styles.footer}>
            <Footer />
          </div>
        </div>
      </body>
    </html>
  );
}
